#\u7AEF\u53E3
server:
  port: 9999

spring:
  thymeleaf:
#   \u5173\u95ED\u7F13\u5B58
    cache: false
#\u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckillapp?useUnicode=true&characterEncoding=utf8&serverTImezone=Asia/Shanghai
    username: root
    password: Root
    hikari:
#     \u4ECE\u8FDE\u63A5\u6C60\u8FD4\u56DE\u7684\u8FDE\u63A5\u81EA\u52A8\u63D0\u4EA4
      auto-commit: true
#     \u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      minimum-idle: 5
#     \u7A7A\u95F2\u8FDE\u63A5\u6700\u5927\u5B58\u6D3B\u65F6\u95F4(30 min)
      idle-timeout: 1800000
#     \u8FDE\u63A5\u6700\u5927\u5B58\u6D3B\u65F6\u95F4(30 min)
      max-lifetime: 1800000
#     \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4(30 sec)
      connection-timeout: 30000
#     \u8FDE\u63A5\u6C60\u540D\u5B57
      pool-name: DataHikariCP
#     \u6700\u5927\u8FDE\u63A5\u6570
      maximum-pool-size: 10
#     \u6D4B\u8BD5\u8FDE\u63A5\u662F\u5426\u53EF\u7528\u7684\u67E5\u8BE2\u8BED\u53E5
      connection-test-query: SELECT 1

mybatis-plus:
  global-config:
#    \u5173\u95EDbanner
    banner: false
# \u5BF9\u5E94\u5B9E\u4F53\u4F4D\u7F6E
  type-aliases-package: com.project.seckill.domain
#  mapper.xml\u4F4D\u7F6E
  mapper-locations: classpath*:/mapper/*Mapper.xml

#\u6253\u5370SQL\u8BED\u53E5
logging:
  level:
    com.project.seckill.mapper: debug
