# 更改端口
server:
  port: 9999

spring:
  thymeleaf:
#   关闭thymeleaf缓存
    cache: false
# 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckilldemo?useUnicode=true&characterEncoding=utf8&serverTImezone=Asia/Shanghai
    username: root
    password: Root
#    配置数据库连接池
    hikari:
#     连接自动提交
      auto-commit: true
#     最小空闲连接数
      minimum-idle: 5
#     空闲连接最大存活时间 30min
      idle-timeout: 1800000
#     连接最大存活时间 30min
      max-lifetime: 1800000
#     连接超时时间 30sec
      connection-timeout: 30000
#     连接池名称
      pool-name: DataHikariCP
#     最大连接数
      maximum-pool-size: 10
#     测试连接是否可用
      connection-test-query: SELECT 1

mybatis-plus:
  global-config:
#   关闭mybatis-plus banner
    banner: false
# 配置生成domain位置
  type-aliases-package: com.project.seckill.domain
# 配置mapper.xml文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml

#打印SQL语句
logging:
  level:
    com.project.seckill.mapper: debug
